// frontend/src/components/RelationshipList.vue
<template>
    <v-card outlined class="mb-4 relationship-section">
        <v-card-title>
            Relationships
            <v-icon class="cursor-pointer" @click="toggleCollapse">
                {{ isCollapsed ? 'mdi-chevron-down' : 'mdi-chevron-up' }}
            </v-icon>
        </v-card-title>

        <v-expand-transition>
            <div v-if="!isCollapsed">
                <v-card-text>
                    <!-- List of Existing Relationships -->
                    <v-list dense>
                        <v-list-item dense v-for="relationship in relationships" :key="relationship.ID" class="field-label">
                            <div v-if="relationship.related_contact_id != null && relationship.related_contact">
                                <strong>{{ relationship.type }}: </strong>
                                {{ relationship.related_contact.firstname }}
                                {{ relationship.related_contact.lastname }}
                                <span v-if="relationship.related_contact.birthday">( {{
                                    formatBirthday(relationship.birthday) }}
                                    )</span>
                            </div>

                            <div v-else>
                                <strong>{{ relationship.type }}: </strong>
                                {{ relationship.name }}
                                <span v-if="relationship.birthday">({{ formatBirthday(relationship.birthday) }})</span>
                            </div>

                            <template v-slot:append>
                                <v-icon small class="edit-icon ml-2"
                                    @click="editRelationship(relationship)">mdi-pencil</v-icon>
                                <v-icon small class="delete-icon ml-2" color="error"
                                    @click="deleteRelationship(relationship.ID)">mdi-delete</v-icon>
                            </template>
                        </v-list-item>
                        <!-- Icon to Add New Relationship -->
                        <v-icon small class="add-circle-icon mt-2" @click="openAddRelationshipDialog">
                            mdi-plus-circle
                        </v-icon>
                    </v-list>
                </v-card-text>
            </div>
        </v-expand-transition>

        <!-- Dialog to Add/Edit Relationship -->
        <v-dialog v-model="showAddRelationshipDialog" max-width="500px">
            <v-card>
                <v-card-title>{{ editingRelationship ? 'Edit Relationship' : 'Add Relationship' }}</v-card-title>
                <v-card-text>
                    <v-tabs v-model="activeTab" class="mb-4">
                        <v-tab value="manual">Manual Entry</v-tab>
                        <v-tab value="existing">Select Existing Contact</v-tab>
                    </v-tabs>

                    <v-window v-model="activeTab">
                        <!-- Manual Entry Tab -->
                        <v-window-item value="manual">
                            <v-form>
                                <v-combobox v-model="relationshipForm.type" :items="relationshipTypes"
                                    label="Relationship Type" outlined color="blue-grey-lighten-2"
                                    required></v-combobox>
                                <v-text-field v-model="relationshipForm.name" label="Name" required></v-text-field>
                                <v-select v-model="relationshipForm.gender" :items="['Male', 'Female', 'Unknown']"
                                    label="Gender" required></v-select>
                                <v-text-field v-model="formattedBirthday" label="Birthday (Optional)"
                                    placeholder="DD.MM.YYYY or DD.MM." :error-messages="birthdayError"
                                    @blur="validateBirthday"></v-text-field>
                            </v-form>
                        </v-window-item>

                        <!-- Select Existing Contact Tab -->
                        <v-window-item value="existing">
                            <v-form>
                                <v-select v-model="relationshipForm.type" :items="relationshipTypes"
                                    label="Relationship Type" required></v-select>
                                <v-autocomplete v-model="relationshipForm.related_contact" :items="filteredContacts"
                                    item-title="name" item-value="ID" label="Select Existing Contact" return-object
                                    outlined color="blue-grey-lighten-2" required>

                                    <!-- Dropdown Item Slot -->
                                    <template v-slot:item="{ props, item }">
                                        <v-list-item v-bind="props" :key="item.ID"
                                            :prepend-avatar="getAvatarURL(item.value)" :text="item.title"></v-list-item>
                                    </template>
                                </v-autocomplete>
                            </v-form>
                        </v-window-item>
                    </v-window>
                </v-card-text>
                <v-card-actions>
                    <v-spacer></v-spacer>
                    <v-btn @click="closeAddRelationshipDialog">Cancel</v-btn>
                    <v-btn color="primary" @click="saveRelationship">{{ editingRelationship ? 'Save' : 'Add' }}</v-btn>
                </v-card-actions>
            </v-card>
        </v-dialog>
    </v-card>
</template>

<script>
import contactService from '@/services/contactService';
import { backendURL } from '@/services/api';

export default {
    name: 'RelationshipList',
    props: {
        contactId: {
            required: true,
        },
    },
    data() {
        return {
            activeTab: 'manual', // Track which tab is currently active
            showAddRelationshipDialog: false,
            editingRelationship: null,
            relationships: [],
            relationshipForm: {
                name: '',
                type: '',
                gender: '',
                birthday: '',
                related_contact: null,
            },
            birthdayError: '',
            relationshipTypes: ['Child', 'Parent', 'Sibling', 'Partner', 'Friend'],
            contacts: [], // Contacts for existing contact selection
            backendURL,
            isCollapsed: false,
        };
    },
    computed: {
        filteredContacts() {
            return this.contacts;
        },
        formattedBirthday: {
            // Getter: Format the date for display
            get() {
                // Convert YYYY-MM-DD to DD.MM.YYYY
                if (!this.relationshipForm.birthday) return ""; // Handle null or empty cases
                const [year, month, day] = this.relationshipForm.birthday.split("-");
                return `${day}.${month}.${year && year !== '0001' ? year : ''}`;
            },
            // Setter: Parse the date back to ISO format
            set(value) {
                if (!value) {
                    this.relationshipForm.birthday = null;
                }
                // Convert DD.MM.YYYY back to YYYY-MM-DD
                const parts = value.split(".");
                if (parts.length === 3) {
                    const [day, month, year] = parts;
                    this.relationshipForm.birthday = `${year || '0001'}-${month.padStart(2, '0')}-${day.padStart(2, '0')}`;
                }
            },
        },
    },
    mounted() {
        this.fetchRelationships();

        this.loadContacts();
        //TODO: only execute the function when a relationship is added
    },
    methods: {
        toggleCollapse() {
            this.isCollapsed = !this.isCollapsed;
        },
        async loadContacts() {
            try {
                const response = await contactService.getContacts({
                    fields: ['ID', 'firstname', 'lastname'],
                    limit: 5000,
                });
                this.contacts = response.data.contacts.map(contact => ({
                    ID: contact.ID,
                    name: `${contact.firstname} ${contact.lastname}`,
                }));
            } catch (error) {
                console.error('Error fetching contacts:', error);
            }
        },
        async fetchRelationships() {
            try {
                const response = await contactService.getRelationships(this.contactId)
                this.relationships = response.data.relationships
            } catch (error) {
                console.error('Error fetching relationships:', error);
            }
        },
        openAddRelationshipDialog() {
            this.showAddRelationshipDialog = true;
            this.editingRelationship = null;
            this.resetRelationshipForm();
        },
        editRelationship(relationship) {
            this.showAddRelationshipDialog = true;
            this.editingRelationship = relationship;
            this.relationshipForm = { ...relationship };
        },
        async saveRelationship() {
            const relationshipData = {
                type: null,
                name: null,
                gender: null,
                birthday: null,
                contact_id: this.contactId,
                related_contact_id: null,
            };

            try {
                if (this.activeTab === 'manual') {
                    if (!this.relationshipForm.name || !this.relationshipForm.type) {
                        throw new Error('Please provide both name and relationship type.');
                    }

                    if (this.birthdayError) {
                        throw new Error('Invalid birthday format.');
                    }

                    relationshipData.type = this.relationshipForm.type;
                    relationshipData.name = this.relationshipForm.name;
                    relationshipData.gender = this.relationshipForm.gender;
                    relationshipData.birthday = this.relationshipForm.birthday;

                } else if (this.activeTab === 'existing') {
                    if (!this.relationshipForm.related_contact || !this.relationshipForm.type) {
                        throw new Error('Please select an existing contact and provide the relationship type.');
                    }

                    relationshipData.type = this.relationshipForm.type;
                    relationshipData.related_contact_id = this.relationshipForm.related_contact.ID;
                }

                if (this.editingRelationship) {
                    await contactService.updateRelationship(this.contactId, this.editingRelationship.ID, relationshipData);
                } else {
                    await contactService.addRelationship(this.contactId, relationshipData);
                }

                this.fetchRelationships();
                this.closeAddRelationshipDialog();

                // Reset editing state
                this.editingRelationship = null;

            } catch (error) {
                console.error('Error saving relationship:', error);
            }
        },
        async deleteRelationship(relationshipId) {
            try {
                await contactService.deleteRelationship(this.contactId, relationshipId);
                this.fetchRelationships();
            } catch (error) {
                console.error('Error deleting relationship:', error);
            }
        },
        closeAddRelationshipDialog() {
            this.showAddRelationshipDialog = false;
            this.resetRelationshipForm();
        },
        resetRelationshipForm() {
            this.relationshipForm = {
                type: '',
                name: '',
                gender: '',
                birthday: '',
                related_contact: null,
            };
            this.birthdayError = '';
        },
        validateBirthday() {
            // Regular expression to match "DD.MM.YYYY" or "DD.MM." format
            const datePattern = /^(0[1-9]|[12][0-9]|3[01])\.(0[1-9]|1[0-2])\.(\d{4})?$/;
            if (this.formattedBirthday != null && this.formattedBirthday != "" && !this.formattedBirthday.match(datePattern)) {
                this.birthdayError = "Please enter a valid date in DD.MM.YYYY or DD.MM. format.";
            } else {
                this.birthdayError = '';
            }
        },
        formatBirthday(value) {
            if (!value) return ""; // Handle null or empty cases
            const [year, month, day] = value.split("-");
            return `${day}.${month}.${year && year !== '0001' ? year : ''}`;
        },
        getAvatarURL(ID) {
            return `${this.backendURL}/contacts/${ID}/profile_picture.jpg`;
        },
    },
};
</script>

<style scoped>
.field-label {
    display: flex;
    align-items: center;
    justify-content: space-between;
}

.v-list-item .edit-icon,
.v-list-item .delete-icon {
    opacity: 0;
    /* Hide icons by default */
    transition: opacity 0.3s ease;
    cursor: pointer;
}

.v-list-item:hover .edit-icon,
.v-list-item:hover .delete-icon {
    opacity: 1;
    /* Show icons on hover */
}

.cursor-pointer {
  cursor: pointer;
}

</style>

// frontend/src/lib/components/RelationshipList.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { contactService } from '$lib/services/contactService';
  import { Button, Card, Input, Select, Textarea, Modal, ButtonGroup, Badge, Tabs, TabItem } from 'flowbite-svelte';
  import { PlusOutline, EditOutline, TrashBinOutline, CheckOutline, CloseOutline, ChevronDownOutline, ChevronUpOutline } from "flowbite-svelte-icons";
  import ProfilePicture from '$lib/components/ProfilePicture.svelte';

  // Props
  let { contactId } = $props<{
    contactId: number;
  }>();

  // State
  let relationships = $state<any[]>([]);
  let loading = $state(false);
  let error = $state<string | null>(null);
  let showModal = $state(false);
  let isCollapsed = $state(false);
  let activeTab = $state('manual');
  let editingRelationship = $state<any>(null);

  // Form state
  let relationshipForm = $state<{
    type: string;
    name: string;
    gender: string;
    birthday: string;
    related_contact_id: number | null;
    related_contact: { value: any; name: string } | null;
  }>({
    type: '',
    name: '',
    gender: '',
    birthday: '',
    related_contact_id: null,
    related_contact: null
  });

  // Available contacts for selection
  let availableContacts = $state<any[]>([]);

  // Relationship types
  const relationshipTypes = [
    'Parent', 'Child', 'Sibling', 'Spouse', 'Partner', 'Friend', 
    'Colleague', 'Neighbor', 'Relative', 'Acquaintance', 'Other'
  ];

  const genderOptions = ['Male', 'Female', 'Other', 'Prefer not to say'];

  onMount(async () => {
    await fetchRelationships();
    await loadAvailableContacts();
  });

  async function fetchRelationships() {
    loading = true;
    error = null;
    
    try {
      const response = await contactService.getRelationships(contactId);
      relationships = response.relationships || [];
    } catch (err) {
      console.error('Error fetching relationships:', err);
      error = err instanceof Error ? err.message : 'Failed to load relationships';
    } finally {
      loading = false;
    }
  }

  async function loadAvailableContacts() {
    try {
      const response = await contactService.getContacts({
        fields: ['ID', 'firstname', 'lastname'],
        limit: 100
      });
      availableContacts = response.contacts
        .filter(contact => contact.ID !== contactId)
        .map(contact => ({
          value: contact.ID,
          name: `${contact.firstname} ${contact.lastname}`,
          ...contact
        }));
    } catch (err) {
      console.error('Error loading contacts:', err);
    }
  }

  function formatBirthday(birthday: string | undefined): string {
    if (!birthday) return '';
    const [year, month, day] = birthday.split('-');
    return `${day}.${month}.${year !== '0001' ? year : ''}`;
  }

  function parseBirthday(formattedBirthday: string): string | null {
    if (!formattedBirthday.trim()) return null;
    
    const datePattern = /^(0[1-9]|[12][0-9]|3[01])\.(0[1-9]|1[0-2])\.(\d{4})?$/;
    const match = formattedBirthday.match(datePattern);
    
    if (match) {
      const [, day, month, year] = match;
      return `${year || '0001'}-${month}-${day}`;
    }
    
    return null;
  }

  function openAddModal() {
    editingRelationship = null;
    resetForm();
    showModal = true;
  }

  function openEditModal(relationship: any) {
    editingRelationship = relationship;
    relationshipForm = {
      type: relationship.type || '',
      name: relationship.name || '',
      gender: relationship.gender || '',
      birthday: formatBirthday(relationship.birthday),
      related_contact_id: relationship.related_contact_id || null,
      related_contact: relationship.related_contact ? {
        value: relationship.related_contact.ID,
        name: `${relationship.related_contact.firstname} ${relationship.related_contact.lastname}`
      } : null
    };
    
    activeTab = relationship.related_contact_id ? 'existing' : 'manual';
    showModal = true;
  }

  function resetForm() {
    relationshipForm = {
      type: '',
      name: '',
      gender: '',
      birthday: '',
      related_contact_id: null,
      related_contact: null
    };
    activeTab = 'manual';
  }

  function closeModal() {
    showModal = false;
    resetForm();
    editingRelationship = null;
  }

  async function saveRelationship() {
    try {
      const relationshipData: any = {
        type: relationshipForm.type,
        contact_id: contactId,
        name: null,
        gender: null,
        birthday: null,
        related_contact_id: null
      };

      if (activeTab === 'manual') {
        if (!relationshipForm.name || !relationshipForm.type) {
          error = 'Please provide both name and relationship type.';
          return;
        }

        relationshipData.name = relationshipForm.name;
        relationshipData.gender = relationshipForm.gender || null;
        relationshipData.birthday = parseBirthday(relationshipForm.birthday);
      } else if (activeTab === 'existing') {
        if (!relationshipForm.related_contact || !relationshipForm.type) {
          error = 'Please select an existing contact and provide the relationship type.';
          return;
        }

        relationshipData.related_contact_id = relationshipForm.related_contact.value;
      }

      if (editingRelationship) {
        await contactService.updateRelationship(contactId, editingRelationship.ID, relationshipData);
      } else {
        await contactService.addRelationship(contactId, relationshipData);
      }

      await fetchRelationships();
      closeModal();
      error = null;
    } catch (err) {
      console.error('Error saving relationship:', err);
      error = err instanceof Error ? err.message : 'Failed to save relationship';
    }
  }

  async function deleteRelationship(relationshipId: number) {
    if (!confirm('Are you sure you want to delete this relationship?')) {
      return;
    }

    try {
      await contactService.deleteRelationship(contactId, relationshipId);
      await fetchRelationships();
      error = null;
    } catch (err) {
      console.error('Error deleting relationship:', err);
      error = err instanceof Error ? err.message : 'Failed to delete relationship';
    }
  }

  function toggleCollapse() {
    isCollapsed = !isCollapsed;
  }
</script>

<Card class="mb-4">
  <div class="flex items-center justify-between mb-4">
    <h3 class="text-lg font-semibold text-gray-900 dark:text-white">Relationships</h3>
    <button 
      class="p-1 rounded hover:bg-gray-100 dark:hover:bg-gray-700"
      onclick={toggleCollapse}
    >
      {#if isCollapsed}
        <ChevronDownOutline class="w-4 h-4" />
      {:else}
        <ChevronUpOutline class="w-4 h-4" />
      {/if}
    </button>
  </div>

  {#if !isCollapsed}
    {#if loading}
      <p class="text-gray-500">Loading relationships...</p>
    {:else if error}
      <div class="p-4 mb-4 text-sm text-red-700 bg-red-100 rounded-lg dark:bg-red-200 dark:text-red-800">
        <span class="font-medium">Error!</span> {error}
      </div>
    {:else}
      <div class="space-y-3">
        {#each relationships as relationship}
          <div class="group flex items-center justify-between p-3 bg-gray-50 dark:bg-gray-800 rounded-lg">
            <div class="flex items-center gap-3">
              {#if relationship.related_contact_id && relationship.related_contact}
                <ProfilePicture 
                  contactId={relationship.related_contact.ID} 
                  initials={`${relationship.related_contact.firstname?.charAt(0) || ''}${relationship.related_contact.lastname?.charAt(0) || ''}`}
                  size="sm"
                />
                <div>
                  <p class="font-medium text-gray-900 dark:text-white">
                    <strong>{relationship.type}:</strong> 
                    {relationship.related_contact.firstname} {relationship.related_contact.lastname}
                  </p>
                  {#if relationship.related_contact.birthday}
                    <p class="text-sm text-gray-500">
                      ({formatBirthday(relationship.related_contact.birthday)})
                    </p>
                  {/if}
                </div>
              {:else}
                <div class="w-8 h-8 bg-gray-300 dark:bg-gray-600 rounded-full flex items-center justify-center">
                  <span class="text-sm font-medium text-gray-600 dark:text-gray-300">
                    {relationship.name?.charAt(0)?.toUpperCase() || '?'}
                  </span>
                </div>
                <div>
                  <p class="font-medium text-gray-900 dark:text-white">
                    <strong>{relationship.type}:</strong> {relationship.name}
                  </p>
                  {#if relationship.birthday}
                    <p class="text-sm text-gray-500">
                      ({formatBirthday(relationship.birthday)})
                    </p>
                  {/if}
                </div>
              {/if}
            </div>
            
            <div class="opacity-0 group-hover:opacity-100 transition-opacity flex gap-2">
              <button 
                class="p-1 rounded hover:bg-gray-200 dark:hover:bg-gray-700"
                onclick={() => openEditModal(relationship)}
              >
                <EditOutline class="w-4 h-4 text-gray-500" />
              </button>
              <button 
                class="p-1 rounded hover:bg-gray-200 dark:hover:bg-gray-700"
                onclick={() => deleteRelationship(relationship.ID)}
              >
                <TrashBinOutline class="w-4 h-4 text-red-500" />
              </button>
            </div>
          </div>
        {/each}

        <button 
          class="flex items-center gap-2 p-3 w-full text-left text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300 hover:bg-blue-50 dark:hover:bg-blue-900/20 rounded-lg transition-colors"
          onclick={openAddModal}
        >
          <PlusOutline class="w-4 h-4" />
          Add Relationship
        </button>
      </div>
    {/if}
  {/if}
</Card>

<!-- Add/Edit Relationship Modal -->
<Modal bind:open={showModal} size="md" autoclose={false}>
  <div class="p-6">
    <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-4">
      {editingRelationship ? 'Edit Relationship' : 'Add Relationship'}
    </h3>

    <Tabs style="underline" class="mb-4">
      <TabItem value="manual" title="Manual Entry" />
      <TabItem value="existing" title="Existing Contact" />
    </Tabs>

    {#if activeTab === 'manual'}
      <div class="space-y-4">
        <div>
          <label for="relationship-type-existing" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            Relationship Type
          </label>
          <Select 
            id="relationship-type-existing"
            bind:value={relationshipForm.type}
            items={relationshipTypes.map(type => ({ value: type, name: type }))}
            placeholder="Select relationship type"
          />
        </div>

        <div>
          <label for="relationship-name" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            Name
          </label>
          <Input 
            id="relationship-name"
            bind:value={relationshipForm.name}
            placeholder="Enter name"
          />
        </div>

        <div>
          <label for="relationship-gender" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            Gender
          </label>
          <Select 
            id="relationship-gender"
            bind:value={relationshipForm.gender}
            items={genderOptions.map(gender => ({ value: gender, name: gender }))}
            placeholder="Select gender"
          />
        </div>

        <div>
          <label for="relationship-birthday" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            Birthday
          </label>
          <Input 
            id="relationship-birthday"
            bind:value={relationshipForm.birthday}
            placeholder="DD.MM.YYYY or DD.MM."
          />
        </div>
      </div>
    {:else}
      <div class="space-y-4">
        <div>
          <label for="relationship-type-existing-tab" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            Relationship Type
          </label>
          <Select 
            id="relationship-type-existing-tab"
            bind:value={relationshipForm.type}
            items={relationshipTypes.map(type => ({ value: type, name: type }))}
            placeholder="Select relationship type"
          />
        </div>

        <div>
          <label for="relationship-existing-contact" class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            Existing Contact
          </label>
          <Select 
            id="relationship-existing-contact"
            bind:value={relationshipForm.related_contact}
            items={availableContacts}
            placeholder="Select existing contact"
          />
        </div>
      </div>
    {/if}

    <div class="flex justify-end gap-3 mt-6">
      <Button color="light" onclick={closeModal}>
        Cancel
      </Button>
      <Button color="blue" onclick={saveRelationship}>
        {editingRelationship ? 'Save Changes' : 'Add Relationship'}
      </Button>
    </div>
  </div>
</Modal>
